### ISSUE TITLE
Graph generation tasks

### ISSUE THREAD

**Issue by JanineCHEN** [shamim-hussain/egt_pytorch#4]
Thank you for this great work!
Can this framework be adopted for graph generation tasks? Thanks!

**Comment by shamim-hussain** [comment]
Of course, this is a very general architecture - suitable for any
graph-related task. I would argue it is more suitable for graph generation
than convolutional GNNs because it directly outputs edge embeddings, so you
could directly generate both nodes and edges. However, the only limiting
factor is the size of the graph, because of the quadratic computational
complexity of transformers.

**Comment by JanineCHEN** [comment]
> Of course, this is a very general architecture - suitable for any graph-related task. I would argue it is more suitable for graph generation than convolutional GNNs because it directly outputs edge embeddings, so you could directly generate both nodes and edges. However, the only limiting factor is the size of the graph, because of the quadratic computational complexity of transformers.

Hi @shamim-hussain , great thanks for your quick response, I will give it a try :+1:
