### ISSUE TITLE
NODE_FEATURES_OFFSET and EDGE_FEATURES_OFFSET

### ISSUE THREAD

**Issue by JanineCHEN** [shamim-hussain/egt_pytorch#5]
https://github.com/shamim-hussain/egt_pytorch/blob/1e243d6c94c572bde6c5d1456c2152e5852091e7/lib/data/graph_dataset/structural_dataset.py#L34

Hi @shamim-hussain , I'm trying to adopt this nice repo to my graph generation project, and I'm curious about the purpose of having the `NODE_FEATURES_OFFSET` and `EDGE_FEATURES_OFFSET` preprocess steps to the node and edge features. Maybe I have overlooked something, yet I could not find an explanation in the [paper](https://arxiv.org/pdf/2108.03348.pdf) related to these two offset preprocess steps.

It would be very much appreciated if you could advise on the purpose of these offset preprocess steps if it is convenient for you. Thank you!

**Comment by shamim-hussain** [comment]
Since we had multiple sets of node and edge features in molecular graphs,
instead of using multiple embedding layers we went with separating the
positions of the embeddings for different sets of features with an offset.
For example, if we have 3 edge features with a number of embeddings 3,2,4
if we separate them by an offset of 4 (max size), we can use a single layer
to embed all features.

In summary, this is an efficiency trick in order to embed different sets of
features using the same embedding layer. You can always ignore this and use
multiple embedding layers or you might not need to worry about this at all
if you have a single set of features for your nodes/edges.

Note also that this is related to how you form the input embeddings from
the input features - i.e., it is not directly related to the EGT
architecture.

**Comment by JanineCHEN** [comment]
Thank you very much @shamim-hussain , for your detailed and prompt explanation. Well understood :-P
